---
# Rename file to secrets.yml to get started for development or test.

development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: <use `rake generate:session_secret`>
  MSG_KEY: <use `rake newkey:msg`>
  REDISCLOUD_URL: redis://localhost:6379/0

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: <use `rake generate:session_secret`>
  MSG_KEY: <use `rake newkey:msg`>
  REDISCLOUD_URL: redis://localhost:6379/0

production:
  API_URL: <set to production API root ending in /api/v1>
  APP_URL: <set to production app URL>
  SESSION_SECRET: <use `rake generate:session_secret`>
  MSG_KEY: <use `rake newkey:msg`>
  REDISCLOUD_URL: <set by `rediscloud` add-on>
